service: os-env-test-wang
#jenkins-ope:removetest12313
provider:
  name: aws
  runtime: python2.7

  stage: dev
  region: ap-northeast-1
  memorySize: 128
  timeout: 40

  role: arn:aws:iam::056530783435:role/gid-tag-check-project-0022001537
    
functions:
  sesSender:
    handler: sestest.lambda_handler
    name: sestest

    
