service: test-for-git-update # NOTE: update this with your service name


provider:
  name: aws
  runtime: python2.7

  region: ap-northeast-1

functions:
  test:
    handler: handler.hello
    name: 0022001550-test-wang
    events:
      - schedule:
          rate: cron(1 10 ? * MON *)
          enabled: true
    
