service: ctq-sls-iam-test # NOTE: update this with your service name


provider:
  name: aws
  runtime: python2.7
  profile: wang-test-aws-cli-config
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        -  "ec2:*"
      Resource: "*"
  region: ap-northeast-1

functions:
  test:
    handler: handler.hello
    name: 0022001537-test-iam-role
    events:
      - schedule:
          rate: cron(1 10 ? * MON *)
          enabled: true
